// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsIoXNo4x8MPKpUD8bF7OEz3ktWdFLR-0',
    appId: '1:587329782370:android:154899e1bacfbfff67473b',
    messagingSenderId: '587329782370',
    projectId: 'mental-health-cecad',
    databaseURL: 'https://mental-health-cecad-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mental-health-cecad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQKTLL4m_UgzNajUM9UNIv015r2fkxqTY',
    appId: '1:587329782370:ios:72a2b2795b0f031e67473b',
    messagingSenderId: '587329782370',
    projectId: 'mental-health-cecad',
    databaseURL: 'https://mental-health-cecad-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mental-health-cecad.firebasestorage.app',
    iosClientId: '587329782370-5k29nrtk2o4ohkva6k2sd821vcu6fn2a.apps.googleusercontent.com',
    iosBundleId: 'com.example.mindnest',
  );
}
